### ISSUE TITLE
plistlib deprecation warning

### ISSUE THREAD

**Issue by frankrolf** [yanone/speedpunk#1]
`plistlib` has changed slightly in Python 3, to produce the following warning on (RF 3.4) startup:

```
Installing 'SpeedPunk' report:
SpeedPunk.roboFontExt/lib/deYanoneRoboFontSpeedpunk/speedpunklib.py:237: DeprecationWarning: The readPlist function is deprecated, use load() instead
```

To solve the issue, [this line](https://github.com/yanone/speedpunk/blob/master/SpeedPunk.roboFontExt/lib/deYanoneRoboFontSpeedpunk/speedpunklib.py#L237) would need to be changed to something like
```
with open(os.path.join(os.path.dirname(__file__), '..', '..', 'info.plist'), 'rb') as pl_file:
    plist = plistlib.load(pl_file)
```

I think Glyphs still uses Python 2.7, and I don’t know if plistlib will just accept the new way of loading files. I am not sure if you’d want to introduce some `if`/`else` calls, therefore I opened this issue rather than sending a PR straight away.

**Comment by schriftgestalt** [comment]
The `speedpunklib.py` files in the RF extension and in the Glyphs plugins are quite different already. So changing that shouldn’t hurt. 
It could be "fixed" when someone unifies the files again.

**Comment by frankrolf** [comment]
Okay – Interesting. I opened this issue after reading [this paragraph](https://github.com/yanone/speedpunk#contribution):

> I accept Pull Requests under the condition that utmost care is taken as to keeping the speedpunklib library for both Glyphs and RoboFont versions inside this repository identical. Maybe contact me first, because I may want to sort out things first.

**Comment by schriftgestalt** [comment]
I just checked. `plistlib.load()` is not available in python 2.

**Comment by yanone** [comment]
> Okay – Interesting. I opened this issue after reading [this paragraph](https://github.com/yanone/speedpunk#contribution):
> 
> > I accept Pull Requests under the condition that utmost care is taken as to keeping the speedpunklib library for both Glyphs and RoboFont versions inside this repository identical. Maybe contact me first, because I may want to sort out things first.

This paragraph has been written in the future of an alternate reality branch where the lib of the Glyphs and RF version are actually still the same as they used to be in the beginning of Speed Punk.

But in this reality of ours they have slowly grown different, and the paragraph should reflect this, but doesn't.

I just landed in Pakistan for an early start of my xmas holidays, visiting the family of my wife, and I'm currentky curing from a dreadful overnight flight. 
If you know what to do, please submit a PR and I'll just merge it. Either way the actual reunification of the two libs (definitely intended) will have to wait until the new year.

Question: will updates to the repo automatically install in RF?

**Comment by frankrolf** [comment]
Will submit a PR!
Updates to the repo will show as an available update in RF, if  time stamp and version number are changed here:
https://github.com/yanone/speedpunk/blob/master/SpeedPunk.roboFontExt/info.plist

**Comment by schriftgestalt** [comment]
Another Question: When an extension is installed in RF, is it cloning the repo and loading the extension of the repo folder? If so, does it support symlinks? Then we could put the shared code in one place and put symlinks into the extension/plugin.

**Comment by typeworld** [comment]
I'm looking at this now, but I can't even read any output. This has been a problem of mine forever. RoboFont is completely mute. I have to reroute all output to the Console.app, but then it doesn't print deprecation warnings, although I also rerouted `sys.stdout`. I can only see errors and explicit `print()` statements.

You could greatly help me by telling me how to read the plugin’s normal output.
p.s. I recently reinstalled my entire system, but this behavior hasn't changed. I have RF 3.3, and the update doesn't show any new versions, but again, this behavior hasn't changed in years.

What am I doing wrong?

**Comment by frankrolf** [comment]
You can edit the verbosity of RF through the preferences editor:
https://robofont.com/documentation/workspace/preferences-editor/

I get deprecation warnings by having set my `warningsLevel` like this:
```
   # Set a warning level, must be 'default', 'once', 'ignore', 'always'
   "warningsLevel": "default"
```

**Comment by frankrolf** [comment]
@schriftgestalt When an extension is installed, the extension bundle is downloaded from Git and placed in the extensions folder. I don’t know if symlinks are supported, but it might be worth a try!

Another method of sharing code across plugins would be using the RF extension builder, which can be automated as seen here: https://github.com/LettError/editThatNextMasterRoboFontExtension/blob/master/buildExtension.py
