### ISSUE TITLE
Conflicting licensing information

### ISSUE THREAD

**Issue by ctrlcctrlv** [yanone/speedpunk#5]
Repo as a whole has Apache license in the root, but files read:

https://github.com/yanone/speedpunk/blob/215d4595a0c8cd8e58449de352463e4ff1eeed62/SpeedPunk.glyphsReporter/Contents/Resources/speedpunk/speedpunklib.py#L9

Makes it hard to be confident of the actual license. I'm no lawyer so I don't know which license prevails here.

**Comment by yanone** [comment]
Oh. That's a leftover from previous times. Apache 2.0 is correct. Thanks for reporting, I will remove all remaining references.
