### ISSUE TITLE
Does not display anything on first run

### ISSUE THREAD

**Issue by mekkablue** [yanone/speedpunk#7]
* Seems to not respect the registered defaults for its settings, so the first time it runs (or after you delete all SpeedPunk defaults), there is nothing visible after you activate _View > SpeedPunk_
* Current workaround: right click and move _Gain_ slider.

**Comment by RafalBuchner** [comment]
https://github.com/yanone/speedpunk/commit/7a9fbbd956bdd853f83680fe66014926fc90b50e
