### ISSUE TITLE
Freeze on opening .otf

### ISSUE THREAD

**Issue by ai-christoph** [yanone/speedpunk#8]
Hi,

when speedpunk plugin is installed .otf files won’t open.
Glyphs then does not react anymore.
When disabling plug-ins on start or after removing speedpunk it works just fine. 
I then opened an .otf file and saved it as .glyphs.
This file also opens with speedpunk enabled.

Help would be very much appreciated. Thanks in advance.

Glyphs Version 2.6.6. (1352) running on MacOS 11.4

**Comment by mekkablue** [comment]
Can you reproduce it with the latest 2.6.7 beta? Go to _Glyphs > Preferences > Updates,_ activate both checkboxes and press the _Update_ button.

**Comment by ai-christoph** [comment]
Seems to work fine in 2.6.7 (1356).
Thanks for the help and fast feedback.
